# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/CSharpApp.Api/
    - name: Build
      run: dotnet build --no-restore src/CSharpApp.Api/CSharpApp.Api.csproj
    - name: Test
      working-directory: src/CSharpApp.Tests/
      run: dotnet test --no-build --verbosity normal src/CSharpApp.Tests/CSharpApp.Tests.csproj
